{
 "title": "Bench Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "All users on sites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_all_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users on Sites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All System users on Sites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_system_user", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Apps on Bench",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_apps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Apps on Site",
   "type": "stat",
   "gridPos": { "h": 13, "w": 10, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_siteapps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sites on Bench",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bench_sites", "legendFormat": "__auto" }
   ]
  }
 ]
}